### ISSUE TITLE
Separate Wordpress DB and Fresta DB

### ISSUE THREAD

**Issue by avekob** [sics-sse/moped#33]
* wpdb passar logiskt sett till att hantera Wordpress-sidor
* Fresta DB sköter all annan logik och anropas via WebServices, antingen från en php-fil (t.ex. Wordpress) eller t.ex. direkt från Eclipse.

All funktionalitet borde göras via WebServices, medan WP-sidan blir så lättviktig som möjligt.

**Comment by arndtjonasson** [comment]
This is now the case. The server uses a new database fresta2, and wp only fresta. Physically, they may be in the same mysql process, but nothing relies on this.
