### ISSUE TITLE
Create SQL schema

### ISSUE THREAD

**Issue by avekob** [sics-sse/moped#38]
Create an SQL schema file that describes how all tables for the trusted server should be created, e.g. containing rows such as:
"create table Vehicle (id integer, name string, description string, vin string)"

Use this file when the trusted server binaries are launched to create tables unless they already exist.

Also, use the same schema file to create temporary SQLite DBs in junit tests.

**Comment by arndtjonasson** [comment]
Right now, it's new-server/fresta2-schema. Extracted with mysqldump and then modified by hand.
