### ISSUE TITLE
licensing problem with codebench software

### ISSUE THREAD

**Issue by sarankumar1991** [sics-sse/moped#64]
i got 30 day license from mentor graphics and installed it in ubuntu successfully. after changing CROSS_COMPILE path in build.sh file to the location where arm-none-eabi-gcc was present, i executed sh ./build.sh file
but i got flexNet licensing error, saying "no such file or directory exists" and says use LM_LICENSE_FILE to change. i changed the path to license.txt file which was provided by the mentor graphics .
but even after that the same problem exist

**Comment by arndtjonasson** [comment]
We cannot help with this.
